title: Tech Blog
description: My Personal Tech Blog
author: Y.H. Choi
github: https://github.com/milanoderby
about:  NHN Rookie 7기
disqus_shortname: milanoderby
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-github
      link: "https://github.com/milanoderby"
    - icon: fa-facebook
      link: "#"
#    - icon: fa-twitter
#      link: "#"
#    - icon: fa-linkedin
#      link: "#"
#    - icon: fa-stack-exchange
#      link: "#"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
#    - text: XML Feed
#      url: /feed.xml

url: "https://milanoderby.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
